package cn.edu.buaa.jsi.portal;

/**
 * 
 * @author yyq @{2014/10/23}
 *
 */
public class DesData {

	public String node_name;
	public String rm_arguments;

	/**
	 * The DesData class records information of data generated by placement
	 * experiment.The information includes name of the node where the data
	 * belongs to and arguments needed by condor when remove data.
	 * 
	 * @param node_name
	 *            name of the node where the data belongs to
	 * @param rm_arguments
	 *            arguments needed by condor when remove data
	 */
	public DesData(String node_name, String rm_arguments) {
		this.node_name = node_name;
		this.rm_arguments = rm_arguments;
	}

	/**
	 * Returns name of the node where the data belongs to.
	 * 
	 * @return name of the node where the data belongs to
	 */
	public String getNode_name() {
		return node_name;
	}

	/**
	 * Returns the arguments needed by condor when remove data
	 * 
	 * @return arguments needed by condor when remove data
	 */
	public String getRm_arguments() {
		return rm_arguments;
	}

}
